# Server Port Configuration
server.port=8080

# Spring Application Name
spring.application.name=lab12-spring-mvc-student

# Thymeleaf Cache (disable for development)
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Encoding Configuration
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
